name: Random Rationality
favicon: null
layout_spectrum: 0.25689
typography_spectrum: 0.24705
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#c7c7c7'
    - '#515151'
    - '#292929'
  brandStrength: 0.45748401060700417
  lightness: 0.5
  saturation: 0.9796557151712477
  rhythmicContrast: 0.5
purpose: []
